package pe.com.gmd.dokkuapp.domain.orm;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import pe.com.gmd.dokkuapp.domain.orm.USUARIO;
import pe.com.gmd.dokkuapp.domain.orm.TIPO;
import pe.com.gmd.dokkuapp.domain.orm.TARJETA;
import pe.com.gmd.dokkuapp.domain.orm.ESTACION;
import pe.com.gmd.dokkuapp.domain.orm.RUTA;
import pe.com.gmd.dokkuapp.domain.orm.DETALLE_RUTA;
import pe.com.gmd.dokkuapp.domain.orm.NOTIFICACION;

import pe.com.gmd.dokkuapp.domain.orm.USUARIODao;
import pe.com.gmd.dokkuapp.domain.orm.TIPODao;
import pe.com.gmd.dokkuapp.domain.orm.TARJETADao;
import pe.com.gmd.dokkuapp.domain.orm.ESTACIONDao;
import pe.com.gmd.dokkuapp.domain.orm.RUTADao;
import pe.com.gmd.dokkuapp.domain.orm.DETALLE_RUTADao;
import pe.com.gmd.dokkuapp.domain.orm.NOTIFICACIONDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uSUARIODaoConfig;
    private final DaoConfig tIPODaoConfig;
    private final DaoConfig tARJETADaoConfig;
    private final DaoConfig eSTACIONDaoConfig;
    private final DaoConfig rUTADaoConfig;
    private final DaoConfig dETALLE_RUTADaoConfig;
    private final DaoConfig nOTIFICACIONDaoConfig;

    private final USUARIODao uSUARIODao;
    private final TIPODao tIPODao;
    private final TARJETADao tARJETADao;
    private final ESTACIONDao eSTACIONDao;
    private final RUTADao rUTADao;
    private final DETALLE_RUTADao dETALLE_RUTADao;
    private final NOTIFICACIONDao nOTIFICACIONDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uSUARIODaoConfig = daoConfigMap.get(USUARIODao.class).clone();
        uSUARIODaoConfig.initIdentityScope(type);

        tIPODaoConfig = daoConfigMap.get(TIPODao.class).clone();
        tIPODaoConfig.initIdentityScope(type);

        tARJETADaoConfig = daoConfigMap.get(TARJETADao.class).clone();
        tARJETADaoConfig.initIdentityScope(type);

        eSTACIONDaoConfig = daoConfigMap.get(ESTACIONDao.class).clone();
        eSTACIONDaoConfig.initIdentityScope(type);

        rUTADaoConfig = daoConfigMap.get(RUTADao.class).clone();
        rUTADaoConfig.initIdentityScope(type);

        dETALLE_RUTADaoConfig = daoConfigMap.get(DETALLE_RUTADao.class).clone();
        dETALLE_RUTADaoConfig.initIdentityScope(type);

        nOTIFICACIONDaoConfig = daoConfigMap.get(NOTIFICACIONDao.class).clone();
        nOTIFICACIONDaoConfig.initIdentityScope(type);

        uSUARIODao = new USUARIODao(uSUARIODaoConfig, this);
        tIPODao = new TIPODao(tIPODaoConfig, this);
        tARJETADao = new TARJETADao(tARJETADaoConfig, this);
        eSTACIONDao = new ESTACIONDao(eSTACIONDaoConfig, this);
        rUTADao = new RUTADao(rUTADaoConfig, this);
        dETALLE_RUTADao = new DETALLE_RUTADao(dETALLE_RUTADaoConfig, this);
        nOTIFICACIONDao = new NOTIFICACIONDao(nOTIFICACIONDaoConfig, this);

        registerDao(USUARIO.class, uSUARIODao);
        registerDao(TIPO.class, tIPODao);
        registerDao(TARJETA.class, tARJETADao);
        registerDao(ESTACION.class, eSTACIONDao);
        registerDao(RUTA.class, rUTADao);
        registerDao(DETALLE_RUTA.class, dETALLE_RUTADao);
        registerDao(NOTIFICACION.class, nOTIFICACIONDao);
    }
    
    public void clear() {
        uSUARIODaoConfig.getIdentityScope().clear();
        tIPODaoConfig.getIdentityScope().clear();
        tARJETADaoConfig.getIdentityScope().clear();
        eSTACIONDaoConfig.getIdentityScope().clear();
        rUTADaoConfig.getIdentityScope().clear();
        dETALLE_RUTADaoConfig.getIdentityScope().clear();
        nOTIFICACIONDaoConfig.getIdentityScope().clear();
    }

    public USUARIODao getUSUARIODao() {
        return uSUARIODao;
    }

    public TIPODao getTIPODao() {
        return tIPODao;
    }

    public TARJETADao getTARJETADao() {
        return tARJETADao;
    }

    public ESTACIONDao getESTACIONDao() {
        return eSTACIONDao;
    }

    public RUTADao getRUTADao() {
        return rUTADao;
    }

    public DETALLE_RUTADao getDETALLE_RUTADao() {
        return dETALLE_RUTADao;
    }

    public NOTIFICACIONDao getNOTIFICACIONDao() {
        return nOTIFICACIONDao;
    }

}
