package pe.com.gmd.dokkuapp.domain.orm;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DETALLE__RUTA".
 */
public class DETALLE_RUTA {

    private Long id;
    private String Embarque;
    private String Orden;
    private long ruta_id;
    private long estacion_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DETALLE_RUTA() {
    }

    public DETALLE_RUTA(Long id) {
        this.id = id;
    }

    public DETALLE_RUTA(Long id, String Embarque, String Orden, long ruta_id, long estacion_id) {
        this.id = id;
        this.Embarque = Embarque;
        this.Orden = Orden;
        this.ruta_id = ruta_id;
        this.estacion_id = estacion_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmbarque() {
        return Embarque;
    }

    public void setEmbarque(String Embarque) {
        this.Embarque = Embarque;
    }

    public String getOrden() {
        return Orden;
    }

    public void setOrden(String Orden) {
        this.Orden = Orden;
    }

    public long getRuta_id() {
        return ruta_id;
    }

    public void setRuta_id(long ruta_id) {
        this.ruta_id = ruta_id;
    }

    public long getEstacion_id() {
        return estacion_id;
    }

    public void setEstacion_id(long estacion_id) {
        this.estacion_id = estacion_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
