package pe.com.gmd.dokkuapp.domain.orm;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "NOTIFICACION".
 */
public class NOTIFICACION {

    private Long id;
    private String Titulo;
    private String Tipo;
    private String Descripcion;
    private Boolean Estado;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NOTIFICACION() {
    }

    public NOTIFICACION(Long id) {
        this.id = id;
    }

    public NOTIFICACION(Long id, String Titulo, String Tipo, String Descripcion, Boolean Estado) {
        this.id = id;
        this.Titulo = Titulo;
        this.Tipo = Tipo;
        this.Descripcion = Descripcion;
        this.Estado = Estado;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitulo() {
        return Titulo;
    }

    public void setTitulo(String Titulo) {
        this.Titulo = Titulo;
    }

    public String getTipo() {
        return Tipo;
    }

    public void setTipo(String Tipo) {
        this.Tipo = Tipo;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public Boolean getEstado() {
        return Estado;
    }

    public void setEstado(Boolean Estado) {
        this.Estado = Estado;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
