package pe.com.gmd.dokkuapp.domain.orm;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TARJETA".
 */
public class TARJETA {

    private Long id;
    /** Not-null value. */
    private String IdTipo;
    private String Color;
    private String Nombre;
    private String Descripcion;
    private String Requisitos;
    private String PrecioTarjeta;
    private String PrecioViaje;
    private String Dias;
    private long tipo_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TARJETA() {
    }

    public TARJETA(Long id) {
        this.id = id;
    }

    public TARJETA(Long id, String IdTipo, String Color, String Nombre, String Descripcion, String Requisitos, String PrecioTarjeta, String PrecioViaje, String Dias, long tipo_id) {
        this.id = id;
        this.IdTipo = IdTipo;
        this.Color = Color;
        this.Nombre = Nombre;
        this.Descripcion = Descripcion;
        this.Requisitos = Requisitos;
        this.PrecioTarjeta = PrecioTarjeta;
        this.PrecioViaje = PrecioViaje;
        this.Dias = Dias;
        this.tipo_id = tipo_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIdTipo() {
        return IdTipo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdTipo(String IdTipo) {
        this.IdTipo = IdTipo;
    }

    public String getColor() {
        return Color;
    }

    public void setColor(String Color) {
        this.Color = Color;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public String getRequisitos() {
        return Requisitos;
    }

    public void setRequisitos(String Requisitos) {
        this.Requisitos = Requisitos;
    }

    public String getPrecioTarjeta() {
        return PrecioTarjeta;
    }

    public void setPrecioTarjeta(String PrecioTarjeta) {
        this.PrecioTarjeta = PrecioTarjeta;
    }

    public String getPrecioViaje() {
        return PrecioViaje;
    }

    public void setPrecioViaje(String PrecioViaje) {
        this.PrecioViaje = PrecioViaje;
    }

    public String getDias() {
        return Dias;
    }

    public void setDias(String Dias) {
        this.Dias = Dias;
    }

    public long getTipo_id() {
        return tipo_id;
    }

    public void setTipo_id(long tipo_id) {
        this.tipo_id = tipo_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
