package pe.com.gmd.dokkuapp.domain.orm;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "USUARIO".
 */
public class USUARIO {

    private Long id;
    /** Not-null value. */
    private String IdUsuario;
    private String Usuario;
    private String Contrasena;
    private String Dni;
    private String Nombres;
    private String Celular;
    private String email;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public USUARIO() {
    }

    public USUARIO(Long id) {
        this.id = id;
    }

    public USUARIO(Long id, String IdUsuario, String Usuario, String Contrasena, String Dni, String Nombres, String Celular, String email) {
        this.id = id;
        this.IdUsuario = IdUsuario;
        this.Usuario = Usuario;
        this.Contrasena = Contrasena;
        this.Dni = Dni;
        this.Nombres = Nombres;
        this.Celular = Celular;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIdUsuario() {
        return IdUsuario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdUsuario(String IdUsuario) {
        this.IdUsuario = IdUsuario;
    }

    public String getUsuario() {
        return Usuario;
    }

    public void setUsuario(String Usuario) {
        this.Usuario = Usuario;
    }

    public String getContrasena() {
        return Contrasena;
    }

    public void setContrasena(String Contrasena) {
        this.Contrasena = Contrasena;
    }

    public String getDni() {
        return Dni;
    }

    public void setDni(String Dni) {
        this.Dni = Dni;
    }

    public String getNombres() {
        return Nombres;
    }

    public void setNombres(String Nombres) {
        this.Nombres = Nombres;
    }

    public String getCelular() {
        return Celular;
    }

    public void setCelular(String Celular) {
        this.Celular = Celular;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
